services:
  usp_flyway:
    container_name: usp_flyway
    image: flyway/flyway:latest
#    depends_on:
#      - usp-mysql
    entrypoint: ["flyway", "-url=jdbc:mysql://usp-mysql:3306/usp?allowPublicKeyRetrieval=true", "-user=root", "-password=123456", "-baselineOnMigrate=true", "migrate"]
    volumes:
      - ../flyway/sql_migrations:/flyway/sql
    networks:
      - usp
networks:
  usp:
    external: true
volumes:
  sql_migrations:
# docker-compose -f  docker-compose-files/usp_flyway.yml -p usp_flyway up --build -d
# docker-compose -f docker-compose-files/usp_mysql.yml -f docker-compose-files/usp_flyway.yml up --build -d